##############################################################################
### PyCIAT CONFIGURATION TEMPLATE
##############################################################################
# Copy this template to config.yaml and customize settings for your use case.
# All paths can be absolute or relative to the project root directory.

# Base configuration
base_dir: "/path/to/project/root"  # Absolute path to project root
name: "example_study"              # Study name for outputs

# Path definitions
paths:
  # Input data paths
  locations_file: "data/study_sites.csv"
  soil_profiles: "data/soil_profiles.json"
  soil_shapefile: "data/gis/karnataka_soils.shp"  # For spatial soil lookup
  soil_shapefile_id_column: "SOIL_ID"  # Column in shapefile containing soil ID
  gis_districts: "data/gis/districts.shp"
  gis_karnataka_boundary: "data/gis/karnataka.shp"
  region_mapping: "data/region_mapping.csv"
  experimental_data: "data/experimental/maize_trials.csv"  # For calibration/validation

  # Climate data sources
  climate_sources:
    gcm_nex_cmip6:
      type: "GCM"
      path: "data/climate/gcm_nex_cmip6/"
      metadata:
        resolution: "0.25deg"
        notes: "NEX-GDDP-CMIP6 downscaled data"
    cordex_sa_iitm:
      type: "RCM"
      path: "data/climate/cordex_sa_iitm_rcm/"
      metadata:
        resolution: "50km"
        driving_experiment: "historical, rcp45, rcp85"
        notes: "IITM RegCM4 CORDEX-SA runs"

  # Output directories
  simulation_setup_dir: "simulations/setup"
  simulation_output_dir: "simulations/output"
  hydrus_interface_dir: "simulations/hydrus"  # For HYDRUS-1D integration
  analysis_output_dir: "analysis/results"
  figure_output_dir: "analysis/figures"
  models_dir: "models"
  surrogate_model_dir: "models/surrogates"
  templates_dir: "templates"
  simulation_status_file: "simulations/simulation_status.csv"

# Models to run
crop_models_to_run:
  - "DSSAT"
  - "APSIM"
  - "STICS"

# Model-specific configurations
crop_model_configs:
  DSSAT:
    executable_path: "/path/to/dscsm048.exe"
    maize_module: "MZCER048"
    cultivar_id: "LOCALNK_DSSAT"
    outputs:
      summary: "Summary.OUT"
      plant_gro: "PlantGro.OUT"
      soil_ni: "SoilNi.OUT"
      overview: "Overview.OUT"

  APSIM:
    executable_path: "/path/to/apsim/Models.exe"  # Classic or NextGen
    simulation_template: "apsim_maize_template.apsimx"
    cultivar_id: "LOCALNK_APSIM"
    outputs:
      report_file: "MaizeReport.csv"

  STICS:
    executable_path: "/path/to/stics_executable"
    cultivar_id: "LOCALNK_STICS"
    outputs:
      mod_s: "mod_s.sti"

# Climate configuration
climate:
  active_sources: ["gcm_nex_cmip6"]
  models_to_run: ["ACCESS-ESM1-5", "CNRM-ESM2-1", "EC-Earth3-Veg-LR", "MIROC6"]
  scenarios_to_run: ["ssp245", "ssp585"]
  variables: ["tasmax", "tasmin", "pr", "rsds", "sfcWind", "hurs"]
  calculate_extreme_indices: true
  lat_range: [11.0, 19.0]
  lon_range: [74.0, 79.0]
  historical_period: ["1995-01-01", "2014-12-31"]
  future_periods:
    near_future: ["2024-01-01", "2050-12-31"]
    mid_future: ["2051-01-01", "2075-12-31"]
    far_future: ["2076-01-01", "2100-12-31"]
  use_dask: true

# Simulation configuration
simulation:
  sowing_dates: ["06-15", "06-30", "07-15"]
  baseline_fertilizer_n: 120  # kg/ha total N
  baseline_irrigation_mode: "AUTO"
  baseline_irrigation_threshold_pct: 50
  baseline_irrigation_amount_mm: 25

  # Advanced simulation features
  simulate_biotic_stress: false
  biotic_stress_parameters:
    module: "generic_stress_factor"
    target_variable: "Yield_kg_ha"
    stress_start_doy_offset: 60
    stress_duration_days: 30
    stress_intensity_factor: 0.15

  simulate_soil_carbon: false
  soil_carbon_parameters:
    model_name: "Placeholder_Century"
    initial_soc_ton_ha: 25
    residue_incorporation_pct: 30

  integrate_hydrus: false
  hydrus_parameters:
    hydrus_executable_path: "/path/to/hydrus/H1D_Calc.exe"
    profile_depth_cm: 150
    time_variable_boundary: true

# Adaptation scenarios
adaptations:
  - name: "baseline"
    description: "Current practices"
    settings: {}

  - name: "early_sowing_jun01"
    description: "Shift sowing date to June 1st"
    settings:
      sowing_dates: ["06-01"]

  - name: "drip_irrigation_90eff"
    description: "High efficiency irrigation"
    settings:
      baseline_irrigation_threshold_pct: 70
      baseline_irrigation_amount_mm: 15

  - name: "drought_tolerant_cultivar"
    description: "Hypothetical drought tolerant cultivar"
    settings:
      DSSAT: { cultivar_id: "DROUGHTNK_DSSAT" }
      APSIM: { cultivar_id: "DROUGHTNK_APSIM" }
      STICS: { cultivar_id: "DROUGHTNK_STICS" }

  - name: "residue_retention_50pct"
    description: "Retain 50% crop residues"
    settings:
      soil_carbon_parameters: { residue_incorporation_pct: 50 }

# Analysis configuration
analysis:
  baseline_period_name: "historical"
  reference_period_for_change: ["1995-01-01", "2014-12-31"]

  output_variables:
    - "Yield_kg_ha"
    - "ETc_mm"
    - "Irrigation_mm"
    - "Anthesis_DOY"
    - "Maturity_DOY"
    - "Biomass_kg_ha"
    - "SoilEvap_mm"
    - "NUptake_kg_ha"

  variable_mapping:
    DSSAT:
      Yield_kg_ha: "GWAD"
      ETc_mm: "ETCP"
      Irrigation_mm: "IRCM"
      Anthesis_DOY: "ADAT"
      Maturity_DOY: "MDAT"
      Biomass_kg_ha: "HWAM"
      SoilEvap_mm: "EPCM"
      NUptake_kg_ha: "NICM"

    APSIM:
      Yield_kg_ha: "Yield"
      ETc_mm: "Maize.Evapotranspiration"
      Irrigation_mm: "Maize.Irrigation"
      Anthesis_DOY: "Maize.Phenology.AnthesisDay"
      Maturity_DOY: "Maize.Phenology.MaturityDay"
      Biomass_kg_ha: "Maize.AboveGround.Wt"
      SoilEvap_mm: "Maize.SoilEvap"
      NUptake_kg_ha: "Maize.NUptake"

    STICS:
      Yield_kg_ha: "masec(n)"
      ETc_mm: "cumulbetr"
      Irrigation_mm: "cumulirrig"
      Anthesis_DOY: "istagefloraison"
      Maturity_DOY: "istagematurite"
      Biomass_kg_ha: "maerienne(n)"
      SoilEvap_mm: "cumulesol"
      NUptake_kg_ha: "QNplanteabsorb"

  output_compression: "gzip"

# Parallel processing configuration
parallel:
  use_hpc_env_vars: false
  hpc_task_id_var: "SLURM_ARRAY_TASK_ID"
  hpc_num_tasks_var: "SLURM_ARRAY_TASK_COUNT"
  num_workers: -1

# Machine Learning Surrogate Settings
surrogate_model:
  enabled: false
  model_type: "RandomForest"
  features:
    - "lat"
    - "lon"
    - "soil_id"
    - "baseline_fertilizer_n"
    - "baseline_irrigation_threshold_pct"
    - "AvgTmax_C"
    - "AvgTmin_C"
    - "TotalPrecip_mm"
    - "sowing_doy"
    - "adaptation"
  targets: ["Yield_kg_ha", "Irrigation_mm"]
  hyperparameters:
    n_estimators: 150
    max_depth: 25
    min_samples_split: 5
    min_samples_leaf: 3
    max_features: 0.7
  test_size: 0.2
